version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: ai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./packages/backend/projects:/app/projects
      - ./packages/backend/data:/app/data
    env_file:
      - .env      # loads JWT_SECRET_KEY and SENTRY_DSN

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      args:
        # Pass the VITE_API_BASE_URL from .env for local dev
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: ai-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    env_file:
      - .env      # loads VITE_SENTRY_DSN (only used if you run dev server inside Docker)

# networks:  # optional
#   default:
#     name: aitraineasy_network
#     driver: bridge
